"""Builds supabase/migrations/005_teams_seed.sql from the team lists in this folder.
Run: python3 supabase/seed/build_seed.py"""
from pathlib import Path

HERE = Path(__file__).parent
CDN = "https://a.espncdn.com/i/teamlogos"
# AP Top 25 (college football) at the time the seed was built; the background job refreshes it.
AP_FOOTBALL = ["Texas", "Georgia", "Notre Dame", "Ole Miss", "Indiana", "Miami", "Ohio State", "Alabama", "BYU", "LSU",
               "Texas Tech", "USC", "Penn State", "Tennessee", "Utah", "Louisville", "Iowa", "Michigan", "Missouri",
               "Oregon", "Florida", "SMU", "Texas A&M", "Mississippi State", "Houston"]


def q(v):
    return "null" if v in (None, "") else "'" + str(v).replace("'", "''") + "'"


def rows(name):
    for line in (HERE / name).read_text().splitlines():
        if line.strip() and not line.startswith("#"):
            yield line.split("|")


values = []
for league, full, nick, abbr, color, alt in rows("pro_teams.txt"):
    logo = f"{CDN}/{league}/500-dark/{abbr.lower()}.png"
    values.append((league, full, nick, abbr, "#" + color, "#" + alt, logo))
for tid, full, school, abbr, color in rows("college_teams.txt"):
    logo = f"{CDN}/ncaa/500-dark/{tid}.png"
    for league in ("college-football", "mens-college-basketball"):
        values.append((league, full, school, abbr, ("#" + color) if color else None, None, logo))

seen, deduped = set(), []
for row in values:
    key = (row[0], "".join(c for c in row[1].lower() if c.isalnum()))
    if key not in seen:
        seen.add(key)
        deduped.append(row)
values = deduped

out = ["-- BetBuddy 005: built-in team list (names, colors, logos) + current AP Top 25.",
       "-- ESPN blocks Netlify's servers, so the app no longer depends on fetching this live.",
       "-- Safe to re-run. Generated by supabase/seed/build_seed.py.",
       "",
       "insert into public.teams (league, name_key, full_name, short_name, abbr, color, alt_color, logo)",
       "select league, norm_name(full_name), full_name, short_name, abbr, color, alt_color, logo from (values"]
out.append(",\n".join("  (" + ", ".join(q(v) for v in row) + ")" for row in values))
out += [") as v(league, full_name, short_name, abbr, color, alt_color, logo)",
        "on conflict (league, name_key) do update set",
        "  full_name = excluded.full_name, short_name = excluded.short_name, abbr = excluded.abbr,",
        "  color = coalesce(excluded.color, teams.color), alt_color = coalesce(excluded.alt_color, teams.alt_color),",
        "  logo = excluded.logo, updated_at = now();",
        "",
        "-- AP Top 25 (college football)",
        "update public.teams set rank = null where league = 'college-football' and rank is not null;",
        "update public.teams t set rank = r.rank from (values"]
out.append(",\n".join(f"  ({q(s)}, {i + 1})" for i, s in enumerate(AP_FOOTBALL)))
out += [") as r(school, rank) where t.league = 'college-football' and t.short_name = r.school;", ""]

(HERE.parent / "migrations" / "005_teams_seed.sql").write_text("\n".join(out))
print(f"{len(values)} team rows")
